### ISSUE TITLE
Лаба 2

### ISSUE THREAD

**Issue by irinamatveeva** [Nigota/BDlaby#1]
Хорошим тоном считается запись всех sql команд заглавными буквами, а все остальное малыми. Например, в задании 1 должно быть SELECT ... FROM.... 
Задание 5 - условие "не превышающий", то есть <= , а не <
Задание 10 - нужно выбрать только десять членов, а не всех по алфавиту расставлять.
Задание 11 - не сделано.
Задание 13 - почему именно столько людей? не много ли?
Задание 14 - сами объекты и не выбраны

**Comment by lasbio** [comment]
1. Не выполнен пункт 1 задания ("сохранить в корне проекта") и пункт 5 ("Внесите файл создания базы данных в gitignore")
2. Задание 5,10 - не исправлено.
3.  Задания 11-14 неправильно.

**Comment by Nigota** [comment]
Исправил ошибки :)

**Comment by Nigota** [comment]
Исправил всё

**Comment by lasbio** [comment]
1. .gitignore содержит временные файлы
2. Задания 6, 7 - lower case.
3. Задание 10 - неправильно, комментарий не имеет отношения к задаче.
4. Задние 12 - не верно. "Последняя" == "самая поздняя".
5. Задание 13 - не верно. "Последние вступившие" == имеющие самую позднюю дату регистрации.
6. Задание 14 - не верно. "monthlymaintenance" - стоимость обслуживания, а не стоимость объекта. Есть функции min/max которые работают быстрее.

**Comment by Nigota** [comment]
1. У меня вордовский документ находится в корне проекта, поэтому, когда ворд открыт, создается временный файл. Чтобы случайно его не отправить на гидхаб, я его в .gitignore добавил
2. Остальное исправил

**Comment by lasbio** [comment]
7 - lower case
14 - можно проще, без UNION

**Comment by Nigota** [comment]
Исправил

**Comment by lasbio** [comment]
14 - можно проще, с одним SELECT

**Comment by Nigota** [comment]
Исправил. Получается использовать минимум 2 SELECT. Как сделать с 1 SELECT я не понимаю. Мне ведь надо как-то найти MAX и MIN - это 1 SELECT точно, а потом мне нужно найти названия объектов, чья стоимость соответствует MAX и MIN - это 2 SELECT.

Конечно, я бы мог просто отсортировать выборку, например, по возрастанию и взять просто первый и последний элемент, но mysql не позволяет так делать
