### ISSUE TITLE
Лаб 3

### ISSUE THREAD

**Issue by lasbio** [Nigota/BDlaby#2]
1.  Задание 2 - в базе данных есть несколько разных кортов, не только теннисных.
2.  Задание 4 - не сделано. Подсказка - есть члены клуба, которые вступили без рекомендации . Вывоить надо как ФИО члена, так и ФИО (если есть)  рекомендателя.
3. Задание 6 - не верно.
4. Задние 7 - если не понимаете задания, то подходите и спрашиваете на лабораторной, а не пишете в GitHub/ GitHub предназначена для контроля версий, а не  для общения в чате.

**Comment by Nigota** [comment]
**Исправил**

**Comment by lasbio** [comment]
5 - не верно. в условиях задачи нет требования facid IN (0, 1). Кроме того, могут  быть добавлены корты с номерами 1,2, причем не обязательно теннисные, поскольку в условиях задачи "теннисный" нет.
6 - не точно. Использование IF в WHERE ведет к тому, что выражение будет вычисляться для каждой записи (31) вместо отбора 9 записей по индексу. 
7 не точно. Надо вывести всех членов - подсказка - могут быть двойники (см. Смитов).  Кроме того, но выводить член, рекомендатель.

**Comment by Nigota** [comment]
Исправил

**Comment by Nigota** [comment]
Исправил

**Comment by lasbio** [comment]
7 - условия отбора и сортировки не соответствуют заданию.

**Comment by Nigota** [comment]
Исправил. Также 4 лабу закинул
